name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  mac:
    name: Swift on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
  linux:
    name: Swift ${{ matrix.swift }} on Linux
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-${{ matrix.swift }}-jammy
    strategy:
      matrix:
        swift: ["5.10", "6.1", "6.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        if: "${{ matrix.swift != '5' }}"
        run: swift test -v
  format:
    name: Format
    runs-on: ubuntu-latest
    container: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: swift format lint **/*.swift -r -s
  lint:
    name: lint
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:0.56.2
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: swiftlint
