name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Swift v6
        uses: swift-actions/setup-swift@v2
        with: { swift-version: "6" }
      - name: Lint
        run: swift package plugin swiftlint --reporter github-actions-logging --strict
  build-and-test:
    name: Build & Test (Swift v${{ matrix.swift }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5", "6"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Use Swift v${{ matrix.swift }}"
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Build
        run: swift build
      - name: Test
        if: matrix.swift == '6'
        run: swift test
